spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/wy_practice?characterEncoding=utf8&serverTimezone=UTC
    driverClassName: com.mysql.jdbc.Driver  #springboot2.0默认数据源是Hikari
    username: root
    password: 123456
  jpa:
    database: MySQL
    show-sql: true
    hibernate:
    #  naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

